envVars:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: true
  - key: APP_URL
    generateValue: true
  # Вместо SQLite используем file для сессий
  - key: SESSION_DRIVER
    value: file
  # И не настраиваем базу данных вообще