services:
  - type: web
    name: easycart
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        generateValue: true
    healthCheckPath: /test
    autoDeploy: true