services:
  - type: web
    name: easycart
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://easycart-3opb.onrender.com
      - key: SESSION_DRIVER
        value: file
      - key: DB_CONNECTION
        value: array
    healthCheckPath: /